---
development:
  cloud_name: dbe6vwqbe
  api_key: '431826583695985'
  api_secret: Y7mrN2-2aK37GK9oeLFdpnrovT0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dbe6vwqbe
  api_key: '431826583695985'
  api_secret: Y7mrN2-2aK37GK9oeLFdpnrovT0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dbe6vwqbe
  api_key: '431826583695985'
  api_secret: Y7mrN2-2aK37GK9oeLFdpnrovT0
  enhance_image_tag: true
  static_image_support: false
